import { generateStream } from '../../shared/lib/gemini.js';
import { db } from '../../shared/db/firebase.js';
import { supabase } from '../../shared/db/supabase.js';
import { publish, subscribe } from '../../shared/eventBusClient.js';
import { TOPICS } from '../../event-bus/topics.js';
import { createAgentPayload } from '../../shared/types/AgentPayload.js';
import { validateResolutionOption } from '../types/ResolutionOption.js';
import { findSuppliers } from '../tools/supplierLookup.js';
import { getRoutesForScenario, detectScenario, toGeoJSON } from '../tools/routingTool.js';
import { calculateCostDelta } from '../tools/costCalculator.js';
import { setLastEventAt } from '../state.js';
import { readFileSync } from 'fs'; import { fileURLToPath } from 'url'; import { dirname, join } from 'path';

const __dirname = dirname(fileURLToPath(import.meta.url)); const SYSTEM_PROMPT = readFileSync(join(__dirname, '../agent/prompt.md'), 'utf-8'); const activeStreams = new Map();
export function getStreamText(traceId) { return activeStreams.get(traceId) || null; }

async function processImpactReport(agentPayload) {
	const impactReport = agentPayload.payload, traceId = agentPayload.traceId; const disruption = { location: impactReport.affectedShipments?.[0]?.corridor || 'Pacific', type: 'WEATHER', affectedZones: [] }; const routes = getRoutesForScenario(detectScenario(disruption)); const region = impactReport.affectedShipments?.[0]?.corridor || 'Pacific'; const seaSuppliers = await findSuppliers(region, 'sea-freight'); const airSuppliers = await findSuppliers(region, 'air-freight');
	const balancedCost = calculateCostDelta({ distanceKm: routes.balanced.distanceKm, mode: routes.balanced.mode, baseCostUSD: 50000 }); const fastestCost = calculateCostDelta({ distanceKm: routes.fastest.distanceKm, mode: routes.fastest.mode, baseCostUSD: 50000 }); const cheapestCost = calculateCostDelta({ distanceKm: routes.cheapest.distanceKm, mode: routes.cheapest.mode, baseCostUSD: 50000 });
	const supplierSummary = [...seaSuppliers, ...airSuppliers].map((s) => `- ${s.name} (ID: ${s.id}) | Region: ${s.region} | Reliability: ${s.reliabilityScore}/100`).join('\n');
	const prompt = `${SYSTEM_PROMPT}\n\n## Impact Report\n- Disruption ID: ${impactReport.disruptionId}\n- Cascade Risk: ${impactReport.cascadeRisk}\n- Urgency: ${impactReport.urgency}/10\n- Affected Shipments: ${impactReport.affectedShipments.length}\n- Total Cargo at Risk: $${impactReport.totalCargoAtRiskUSD.toLocaleString()}\n- Analysis: ${impactReport.analysisText}\n\n## Available Rerouting Options\n1. BALANCED — ${routes.balanced.title}: ${routes.balanced.distanceKm}km via ${routes.balanced.mode}, extra ${routes.balanced.timeDeltaHours}h, cost delta $${balancedCost.costDelta.toLocaleString()}\n2. FASTEST — ${routes.fastest.title}: ${routes.fastest.distanceKm}km via ${routes.fastest.mode}, time delta ${routes.fastest.timeDeltaHours}h, cost delta $${fastestCost.costDelta.toLocaleString()}\n3. CHEAPEST — ${routes.cheapest.title}: ${routes.cheapest.distanceKm}km via ${routes.cheapest.mode}, extra ${routes.cheapest.timeDeltaHours}h, cost delta $${cheapestCost.costDelta.toLocaleString()}\n\n## Available Suppliers\n${supplierSummary || 'No suppliers found'}\nGenerate exactly 3 ranked resolution options.`;
	activeStreams.set(traceId, ''); let fullResponse = ''; for await (const chunk of generateStream(prompt)) { fullResponse += chunk; activeStreams.set(traceId, fullResponse); }
	let options; try { options = JSON.parse(fullResponse.replace(/^```(?:json)?\n?/m, '').replace(/\n?```$/m, '').trim()); if (!Array.isArray(options)) throw new Error('Response is not an array'); } catch { options = [{ rank: 1, title: routes.balanced.title, description: 'Balanced reroute option.', costDelta: balancedCost.costDelta, timeDelta: routes.balanced.timeDeltaHours, supplierName: seaSuppliers[0]?.name || 'Trans-Pacific Shipping', supplierId: seaSuppliers[0]?.id || 'sup-002', confidence: 0.75 }, { rank: 2, title: routes.fastest.title, description: 'Fastest reroute option.', costDelta: fastestCost.costDelta, timeDelta: routes.fastest.timeDeltaHours, supplierName: airSuppliers[0]?.name || 'Pacific Air Express', supplierId: airSuppliers[0]?.id || 'sup-001', confidence: 0.8 }, { rank: 3, title: routes.cheapest.title, description: 'Cheapest reroute option.', costDelta: cheapestCost.costDelta, timeDelta: routes.cheapest.timeDeltaHours, supplierName: seaSuppliers[1]?.name || 'Trans-Pacific Shipping', supplierId: seaSuppliers[1]?.id || 'sup-002', confidence: 0.7 }]; }
	const routesByRank = [routes.balanced, routes.fastest, routes.cheapest];
	const fallbackOptions = [
		{ rank: 1, title: routes.balanced.title, description: 'Balanced sea freight reroute.', costDelta: balancedCost.costDelta, timeDelta: routes.balanced.timeDeltaHours, supplierName: seaSuppliers[0]?.name || 'Trans-Pacific Shipping Co.', supplierId: seaSuppliers[0]?.id || 'sup-002', confidence: 0.75 },
		{ rank: 2, title: routes.fastest.title, description: 'Fastest air freight reroute.', costDelta: fastestCost.costDelta, timeDelta: routes.fastest.timeDeltaHours, supplierName: airSuppliers[0]?.name || 'Pacific Air Express', supplierId: airSuppliers[0]?.id || 'sup-001', confidence: 0.80 },
		{ rank: 3, title: routes.cheapest.title, description: 'Cheapest extended sea route.', costDelta: cheapestCost.costDelta, timeDelta: routes.cheapest.timeDeltaHours, supplierName: seaSuppliers[1]?.name || 'Alaska Northern Route Ltd.', supplierId: seaSuppliers[1]?.id || 'sup-003', confidence: 0.70 },
	];
	const validatedOptions = options.slice(0, 3).map((opt, i) => { let safeOpt; try { const normalized = { ...opt, rank: Number(opt.rank), costDelta: parseInt(opt.costDelta, 10) || fallbackOptions[i].costDelta, timeDelta: parseInt(opt.timeDelta, 10) || fallbackOptions[i].timeDelta, confidence: parseFloat(opt.confidence) || fallbackOptions[i].confidence, supplierName: opt.supplierName || fallbackOptions[i].supplierName, supplierId: opt.supplierId || fallbackOptions[i].supplierId }; safeOpt = validateResolutionOption(normalized); } catch (err) { console.warn(`[ResolutionService] Option rank ${i + 1} failed validation, using fallback:`, err.message); safeOpt = fallbackOptions[i]; } return { ...safeOpt, route: toGeoJSON(routesByRank[i]), impactReportId: impactReport.id, disruptionId: impactReport.disruptionId, traceId, selected: false, createdAt: new Date().toISOString() }; });
	const { error: resErr } = await supabase.from('resolutions').upsert({ id: traceId, trace_id: traceId, impact_report_id: impactReport.id, disruption_id: impactReport.disruptionId, cascade_risk: impactReport.cascadeRisk, urgency: impactReport.urgency, total_cargo_at_risk_usd: impactReport.totalCargoAtRiskUSD, analysis_text: impactReport.analysisText, option_count: validatedOptions.length, status: 'pending' }, { onConflict: 'id' });
	if (resErr) console.error('[ResolutionService] Supabase resolutions write failed (non-fatal):', resErr.message);
	const optionRows = validatedOptions.map((opt) => ({ resolution_id: traceId, trace_id: traceId, rank: opt.rank, title: opt.title, description: opt.description, cost_delta: opt.costDelta, time_delta: opt.timeDelta, supplier_id: opt.supplierId || null, supplier_name: opt.supplierName, confidence: opt.confidence, route_geojson: opt.route, transport_mode: opt.route?.properties?.mode || 'sea-freight', selected: false }));
	const { error: optErr } = await supabase.from('resolution_options').upsert(optionRows, { onConflict: 'resolution_id,rank' });
	if (optErr) console.error('[ResolutionService] Supabase resolution_options write failed (non-fatal):', optErr.message);
	const batch = db.batch(); validatedOptions.forEach((opt) => batch.set(db.collection('resolutions').doc(traceId).collection('options').doc(String(opt.rank)), opt)); batch.set(db.collection('resolutions').doc(traceId), { traceId, impactReportId: impactReport.id, disruptionId: impactReport.disruptionId, cascadeRisk: impactReport.cascadeRisk, urgency: impactReport.urgency, totalCargoAtRiskUSD: impactReport.totalCargoAtRiskUSD, analysisText: impactReport.analysisText, optionCount: validatedOptions.length, createdAt: new Date().toISOString(), status: 'pending' }); await batch.commit(); await publish(TOPICS.RESOLUTION_OPTIONS, createAgentPayload('resolution', { traceId, impactReportId: impactReport.id, disruptionId: impactReport.disruptionId, options: validatedOptions }, traceId)); setLastEventAt(new Date().toISOString()); setTimeout(() => activeStreams.delete(traceId), 300000);
}

export function startResolutionSubscriber() { subscribe(TOPICS.IMPACT_REPORTS, (message) => processImpactReport(message).catch((err) => console.error('[ResolutionService] Unhandled error in processImpactReport:', err.message))); }
